### ISSUE TITLE
Error if you meant to create an async function, pass `async: true` as an option.

### ISSUE THREAD

**Issue by aruba-paulkim** [aruba-paulkim/AirRecorder_WEB_UI#2]
SyntaxError: Unexpected token '/' in /Users/paul/AirRecorder_WEB_UI/views/index.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/Users/paul/AirRecorder_WEB_UI/node_modules/ejs/lib/ejs.js:662:12)
    at Object.compile (/Users/paul/AirRecorder_WEB_UI/node_modules/ejs/lib/ejs.js:396:16)
    at handleCache (/Users/paul/AirRecorder_WEB_UI/node_modules/ejs/lib/ejs.js:233:18)
    at tryHandleCache (/Users/paul/AirRecorder_WEB_UI/node_modules/ejs/lib/ejs.js:272:16)
    at View.exports.renderFile [as engine] (/Users/paul/AirRecorder_WEB_UI/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/Users/paul/AirRecorder_WEB_UI/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/paul/AirRecorder_WEB_UI/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/paul/AirRecorder_WEB_UI/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/paul/AirRecorder_WEB_UI/node_modules/express/lib/response.js:1012:7)

**Comment by aruba-paulkim** [comment]
<% include ./header %> ->  <%- include('header') %>
https://prometheo.tistory.com/37
